# values.yaml
global:
  jwtSecret: "sup3rS3cr3tK3y"
  redisHost: "redis-service"
  redisPort: "6379"
  redisChannel: "log_channel"

frontend:
  port: 8080

apis:
  port: 8080

services:
  authApiAddress: "http://authapi-service:80"
  usersApiAddress: "http://usersapi-service:80"
  todosApiAddress: "http://todosapi-service:80"
  zipkinUrl: "http://zipkin-service:9411"

# Puedes agregar aquí las versiones de tus imágenes si lo deseas
images:
  pullPolicy: Always
