# values.yaml
global:
  jwtSecret: "replace-in-production"
  redisHost: "redis-service"
  redisPort: "6379"
  redisChannel: "log_channel"

frontend:
  port: 8080

apis:
  port: 8080

services:
  authApiAddress: "http://authapi-service:80"
  usersApiAddress: "http://usersapi-service:80"
  todosApiAddress: "http://todosapi-service:80"
  zipkinUrl: "http://zipkin-service:9411"


images:
  pullPolicy: Always

resources:
  requests:
    cpu: "100m"      
    memory: "128Mi"  
  limits:
    cpu: "200m"      
    memory: "256Mi"