apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi-deploy
  labels:
    app: authapi
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: authapi
  template: 
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - name: authapi-container
        image: jeanvg/authapi:latest 
        ports:
        - containerPort: 8080 
        env:
        - name: USERS_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: USERS_API_ADDRESS
        - name: AUTH_API_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: APIS_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: ZIPKIN_URL
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: ZIPKIN_URL
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: authapi-service 
spec:
  selector:
    app: authapi 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 
