apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: {{ .Release.Namespace }}
data:
  REDIS_HOST: {{ .Values.global.redisHost | quote }}
  REDIS_PORT: {{ .Values.global.redisPort | quote }}
  REDIS_CHANNEL: {{ .Values.global.redisChannel | quote }}
  FRONTEND_PORT: {{ .Values.frontend.port | quote }}
  APIS_PORT: {{ .Values.apis.port | quote }}
  AUTH_API_ADDRESS: {{ .Values.services.authApiAddress | quote }}
  TODOS_API_ADDRESS: {{ .Values.services.todosApiAddress | quote }}
  USERS_API_ADDRESS: {{ .Values.services.usersApiAddress | quote }}
  ZIPKIN_URL: {{ .Values.services.zipkinUrl | quote }}