apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: frontend
  template: 
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
      - name: front-container
        image: jeanvg/frontend:latest 
        ports:
        - containerPort: 8080 
        
        
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: FRONTEND_PORT
        - name: TODOS_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: TODOS_API_ADDRESS
        - name: AUTH_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: AUTH_API_ADDRESS

---
apiVersion: v1
kind: Service
metadata:
  name: front-service 
spec:
  type: LoadBalancer
  selector:
    app: frontend 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 
