apiVersion: apps/v1
kind: Deployment
metadata:
  name: todosapi-deploy
  labels:
    app: todosapi
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: todosapi
  template: 
    metadata:
      labels:
        app: todosapi 
    spec:
      containers:
      - name: todosapi-container
        image: jeanvg/todosapi:latest
        ports:
        - containerPort: 8080 
        
        env:
        - name: TODO_API_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: APIS_PORT
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: JWT_SECRET
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: REDIS_PORT
        - name: REDIS_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: REDIS_CHANNEL
        - name: ZIPKIN_URL
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: ZIPKIN_URL

---
apiVersion: v1
kind: Service
metadata:
  name: todosapi-service 
spec:
  selector:
    app: todosapi 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 
