apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi-deploy
  labels:
    app: usersapi
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: usersapi
  template: 
    metadata:
      labels:
        app: usersapi 
    spec:
      containers:
      - name: usersapi-container
        image: jeanvg/usersapi:latest
        ports:
        - containerPort: 8080 
        
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: FRONTEND_PORT
        - name: AUTH_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: AUTH_API_ADDRESS
        - name: ZIPKIN_URL
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: ZIPKIN_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: usersapi-service 
spec:
  selector:
    app: usersapi 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 
